### ISSUE TITLE
Conch in arxiv

### ISSUE THREAD

**Issue by seungkyuK** [mahmoodlab/UNI#1]
Thank you for your great work!

I've read your another paper called 'CONCH' in arxiv (https://arxiv.org/pdf/2307.12914.pdf). 
Can I ask you is this work an extension of CONCH?
And if not, are you preparing an additional publication for CONCH?

**Comment by fedshyvana** [comment]
hi @seungkyuK, thank you for your interest in our work! CONCH has also been officially published as of this Tuesday. You can find the corresponding repository here: https://github.com/mahmoodlab/CONCH.
