### ISSUE TITLE
training epoch

### ISSUE THREAD

**Issue by lingxitong** [mahmoodlab/UNI#28]
hello,can you tell me how many epoch you trained , thanks

**Comment by Richarizardd** [comment]
Hi @lingxitong 

We trained with a batch size of 3072 for 125,000 iterations, equivalent to 384M images seen. This would be "3.84 epochs", but note epochs are not effective for communicating pretraining length ([see this thread for more discussion](https://twitter.com/karpathy/status/1508437725514510336)).

For more details, [see the model card for UNI on HF](https://huggingface.co/MahmoodLab/UNI#training-details).
