### ISSUE TITLE
Transform

### ISSUE THREAD

**Issue by JSluo888** [mahmoodlab/UNI#33]
I am wondering if we have to resize to 224, and normalize using the parameters in the readme? If not, how should we determine the values of these parameters?
```
transform = transforms.Compose(
    [
        transforms.Resize(224),
        transforms.ToTensor(),
        transforms.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225)),
    ]
)
```

**Comment by lsnls** [comment]
Hello, I have the same doubt. Please have you solved it？
