### ISSUE TITLE
Higher resolution embedding

### ISSUE THREAD

**Issue by JSluo888** [mahmoodlab/UNI#37]
Hi, I am wondering during your model training, did you split 224*224 images into 16pixel*16pixel patches? If so, is there any way we can get embedding for each 16*16 patch?

**Comment by Richarizardd** [comment]
Hi @JSluo888  - you can get the dense features for the 16x16 patches using ```forward_intermediate```. https://github.com/huggingface/pytorch-image-models/blob/ac3470188b914c5d7a5058a7e28b9eb685a62427/timm/models/vision_transformer.py#L698
