### ISSUE TITLE
Pretraining time

### ISSUE THREAD

**Issue by FabianHoerst** [mahmoodlab/UNI#38]
Hello,

in your paper you mention the hardware requirements in training UNI - could also give a rough estimation on how time consuming the training was? this would help me very much! Thanks in advance!

Fabian

**Comment by Richarizardd** [comment]
Hi @FabianHoerst 

Pretraining time was around ~1024 GPU hours. With 4x8 A100 80 GB GPUs, it took 32 hours.

**Comment by FabianHoerst** [comment]
Thank you very much!
