### ISSUE TITLE
Does 20x magnification correspond to 0.5 microns per pixel?

### ISSUE THREAD

**Issue by GeorgeBatch** [mahmoodlab/UNI#5]
Hello,

Does the 20x magnification correspond to the resolution of 0.5 microns per pixel (mupp)? I am asking because magnification is not standardised, and I have encountered slides from different scanners with 20x magnification, corresponding to a resolution from 0.23 mupp to 0.55 mupp.

Many thanks,
George

**Comment by GeorgeBatch** [comment]
CLAM's [patch extraction script](https://github.com/mahmoodlab/CLAM/blob/master/create_patches_fp.py) allows to specify these things as arguments if you know the levels/magnification/resolution information about the slides. I want to use [tiatoolbox](https://github.com/TissueImageAnalytics/tiatoolbox) functionality to set the resolution to 0.5 mupp to extract patches without parsing the slide metadata first.

**Comment by guillaumejaume** [comment]
20x usually maps to 0.5 um/px. Indeed, variations exist from one scanner to another. Thanks to UNI diverse training dataset, these variations should not have a large downstream impact.

**Comment by GeorgeBatch** [comment]
@guillaumejaume, thank you for your explanation!
