### ISSUE TITLE
access request accepted, authentification succeeded, but weights downloading and model creating failed

### ISSUE THREAD

**Issue by Vz09** [mahmoodlab/UNI#8]
Hi, 

I followed the procedure (access request via huggingface + authentification via login(token) + weights downloading and model creating), but got error with model = timm.create_model("hf-hub:MahmoodLab/uni", pretrained=True, init_values=1e-5, dynamic_img_size=True)

"GatedRepoError: 401 Client Error. (Request ID: Root=1-65fd9fbe-75542d9c27933ae862f55525)

Cannot access gated repo for url https://huggingface.co/MahmoodLab/UNI/resolve/main/config.json.
Repo model MahmoodLab/UNI is gated. You must be authenticated to access it."

that's just like my request has not been accepted yet, but it's not the case (first snapshot).  I also tried to log out relog in hugging face in case these's a update delay....but I still got the same error. Detailed snapshots are shown below, I really don't know where the problem is....could you help me please? I'm using jupyter notebook on servors of my institution.

Thank you

![1711120164210](https://github.com/mahmoodlab/UNI/assets/74318499/2b3beff0-f9f1-4860-ab15-0cede802a2ab)
![1711120377731](https://github.com/mahmoodlab/UNI/assets/74318499/204fbb71-f928-482a-bda0-6b52cd410fd4)
![1711120432472](https://github.com/mahmoodlab/UNI/assets/74318499/936afe3b-2ae9-4137-af0c-e954fcebc5e0)

**Comment by maxmal1** [comment]
If using google collab, run !pip install --upgrade huggingface_lab
